stages:
  - projects

rpgsaga:
  stage: projects
  trigger:
    include: rpgsaga/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
      changes:
        - rpgsaga/**/*
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never

online-shop:
  stage: projects
  trigger:
    include: onlineshop/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
      changes:
        - onlineshop/**/*
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
