image: mcr.microsoft.com/dotnet/sdk:6.0

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"
    - changes:
        - onlineshop/server/**/*

before_script:
  - cd onlineshop/server/

stages:
  - test

test:
  stage: test
  tags:
    - docker
  script:
    - dotnet test -c Release
