image: node:16.13.1

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: false
      changes:
        - onlineshop/client/**/*

before_script:
  - cd onlineshop/client/

stages:
  - lint
  - test

lint:
  stage: lint
  tags:
    - docker
  script:
    - npm install
    - npm run lint

test:
  stage: test
  tags:
    - docker
  script:
    - npm install
    - npm run test
